# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vision_models',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/vision_models',
                'lib_path': 'vision_models'},
  'syms': {'vision_models.core': {'vision_models.core.foo': ('core.html#foo', 'vision_models/core.py')}}}
